version: "3.8"

services:
  flaskapi:
    build: .
    container_name: flaskapi
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: python app.py
    depends_on:
      - redis  

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data 

volumes:
  redis-data:
