version: "3.8"

services:
  flaskapi:
    build: .
    container_name: flaskapi
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      - FLASK_ENV=development

volumes:
  redis-data:
